- name: Configure server
  hosts: hosts
  gather_facts: true
  become: true

  vars_files:
    - ../vars/main.yml
    - ../secrets/vault.yml

  roles:
    - role: ssh
      tags: ssh

    - role: firewall
      tags: firewall

    - role: auditd
      tags: auditd

    - role: updates
      tags: updates

    - role: docker
      tags: docker

    - role: app
      tags: app