- name: Configure server
  hosts: hosts
  gather_facts: true
  become: true

  vars_files:
    - ../vars/main.yml
    - ../secrets/vault.yml

  roles:
    - ssh
    - firewall
    - auditd
    - updates
    - docker
    - app