#!/usr/bin/env bash
# Render ans/inventory/hosts.ini from the Terraform outputs.
#
# Terraform owns the instance and therefore owns its IP; this is the one place
# that address crosses from the Terraform half of the repo into the Ansible
# half, so nothing has to be pasted by hand.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tf_dir="$repo_root/tf"
inventory="$repo_root/ans/inventory/hosts.ini"

ssh_user="${SSH_USER:-admin}"

# Keep whatever key the current inventory points at unless SSH_KEY says otherwise,
# so re-rendering never silently swaps the key out from under you.
ssh_key="${SSH_KEY:-}"
if [[ -z "$ssh_key" && -f "$inventory" ]]; then
	ssh_key="$(sed -n 's/.*ansible_ssh_private_key_file=\([^[:space:]]*\).*/\1/p' "$inventory" | head -1)"
fi
ssh_key="${ssh_key:-$HOME/.ssh/deez2/deez2.pem}"

public_ip="$(terraform -chdir="$tf_dir" output -raw public_ip)"
if [[ -z "$public_ip" ]]; then
	echo "error: terraform output public_ip is empty — has 'terraform apply' run?" >&2
	exit 1
fi

cat > "$inventory" <<INI
# Generated by scripts/inventory.sh from 'terraform output public_ip'.
# Re-run 'make inventory' after any apply that replaces the instance.
[hosts]
server ansible_host=${public_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key}
INI

echo "inventory: server=${public_ip} user=${ssh_user} key=${ssh_key}"
